export type Technology = "Node.js" | "React" | "Next.js" | "TypeScript" | "MongoDB" | "Express" | "Python";

/**
 * Dictionary mapping supported technologies to their respective standard .gitignore templates.
 */
export const gitignoreTemplates: Record<Technology, string> = {
  "Node.js": `
# Node.js
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.pnpm-debug.log*
.env
.env.local
.env.development.local
.env.test.local
.env.production.local
dist/
build/
`,
  "React": `
# React
build/
node_modules/
.env
.env.local
`,
  "Next.js": `
# Next.js
.next/
out/
build/
.env.local
.env.development.local
.env.test.local
.env.production.local
node_modules/
`,
  "TypeScript": `
# TypeScript
*.tsbuildinfo
dist/
`,
  "MongoDB": `
# MongoDB
data/db/
mongodb.log
`,
  "Express": `
# Express
node_modules/
.env
coverage/
`,
  "Python": `
# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST

# Virtual Environments
venv/
env/
ENV/
.env
`,
};

/**
 * Compiles a single .gitignore file from an array of selected technologies.
 * Automatically removes duplicate lines to keep the final output clean.
 * 
 * @param technologies - Array of selected technologies (e.g., ["Node.js", "React"])
 * @returns A formatted string containing the combined .gitignore content.
 */
export const generateGitignore = (technologies: Technology[]): string => {
  if (technologies.length === 0) return "";
  
  const header = "# Generated by GitMate\\n";
  const content = technologies.map(tech => gitignoreTemplates[tech]).join("\\n");
  
  // Remove duplicate lines while preserving order (basic implementation)
  const lines = content.split("\\n");
  const uniqueLines = lines.filter((item, pos) => {
    if (item.trim() === "" || item.startsWith("#")) return true; // keep empty lines and comments
    return lines.indexOf(item) === pos;
  });
  
  return header + uniqueLines.join("\\n");
};
